{
 "title": "Overview",
 "description": "This dashboard acts as a general overview over all hawk information.",
 "tags": [
  "Service Requests",
  "Endpoint Requests"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard acts as a general overview over all hawk information."
   }
  },
  {
   "title": "Endpoint & Service Requests Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Service Requests",
   "type": "piechart",
   "description": "A Chart that shows how often different services were requested in the specified time span. This is an aggregated count over all service endpoints.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "service_requests_table" }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "target": "endpoint_requests_table" }
   ]
  },
  {
   "title": "Endpoint & Service Requests Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Service Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "target": "service_requests_table" }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "target": "endpoint_requests_table" }
   ]
  },
  {
   "title": "Service Initiator Requests",
   "type": "table",
   "description": "A Table that shows the amount of requests of a service drilled down by\nthe initiator service. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  },
  {
   "title": "Endpoint Initiator Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "endpoint_initiator_requests_table"
    }
   ]
  }
 ]
}
{
 "title": "Endpoint Details",
 "description": "This dashboard shows the requests of a specific endpoint over time",
 "tags": [
  "Endpoint Requests",
  "Endpoint Requests Over Time"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoints",
    "label": "Endpoint",
    "query": {
     "query": "{   \"target\": \"endpoints\" }"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the amount of requests of a specific endpoint over time.\\\nOn the top right hand side, the time frame for this analysis is specified.\\\nOn the top left, the graph can be updated for each existing endpoint."
   }
  },
  {
   "title": "Endpoint Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "target": "endpoint_requests_table" }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "payload": "{\"endpoint\":\"$endpoints\"}",
     "target": "requests_time"
    }
   ]
  }
 ]
}
{
 "title": "Field Details",
 "description": "This Dashboard shows detailed information on a specified field.",
 "tags": [
  "Field Endpoints",
  "Field Requests",
  "Field Requests Over Time"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fields",
    "label": "Field",
    "query": {
     "query": "{\"target\":\"fields\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This Dashboard shows detailed information on a specified field.\\\nSelect a privacy related field on the top left.\\\nClick on an endpoint to open a detailed endpoint overview dashboard."
   }
  },
  {
   "title": "Total requests",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "payload": "{\"fields\":[\"$fields\"]}",
     "target": "field_requests"
    }
   ]
  },
  {
   "title": "Field Endpoints",
   "type": "table",
   "description": "The Field Endpoints table is perhaps the most useful overview that hawk core monitor currently provides for the data controller in terms of privacy preserving\ninsights. On the top left can the privacy related field get selected. The Field Endpoints\npanel provides a list of all endpoints that include the selected field in their usages. The\nlist has the endpoint rows overwritten with links to the corresponding endpoint requests\ndashboards.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "payload": "{\"field\":\"$fields\"}",
     "target": "field_endpoints"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "payload": "{\"fields\":[\"$fields\"]}",
     "target": "field_requests_time"
    }
   ]
  }
 ]
}
{
 "title": "Service Requests Graph",
 "description": "This service graph shows all observed services and the amount of API Requests between them.",
 "tags": [
  "Service Graph",
  "Service Initiator Requests"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This service graph shows all observed services and the amount of API Requests between them."
   }
  },
  {
   "title": "Service Graph",
   "type": "novatec-sdg-panel",
   "description": "This service graph shows all observed services and the amount of API Requests between them.",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  },
  {
   "title": "Combined Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    { "target": "requests_time" }
   ]
  },
  {
   "title": "Service Initiator Requests ",
   "type": "table",
   "description": "This shows the amount of requests on a per service drilled down by the initiator service. This overview provides all necessary information to construct the Service Graph panel.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  }
 ]
}