{
 "title": "Field Details",
 "description": "This Dashboard shows detailed information on a specified field.",
 "tags": [
  "Field Endpoints",
  "Field Requests",
  "Field Requests Over Time"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fields",
    "label": "Field",
    "query": {
     "query": "{\"target\":\"fields\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This Dashboard shows detailed information on a specified field.\\\nSelect a privacy related field on the top left.\\\nClick on an endpoint to open a detailed endpoint overview dashboard."
   }
  },
  {
   "title": "Total requests",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "payload": "{\"fields\":[\"$fields\"]}",
     "target": "field_requests"
    }
   ]
  },
  {
   "title": "Field Endpoints",
   "type": "table",
   "description": "The Field Endpoints table is perhaps the most useful overview that hawk core monitor currently provides for the data controller in terms of privacy preserving\ninsights. On the top left can the privacy related field get selected. The Field Endpoints\npanel provides a list of all endpoints that include the selected field in their usages. The\nlist has the endpoint rows overwritten with links to the corresponding endpoint requests\ndashboards.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "payload": "{\"field\":\"$fields\"}",
     "target": "field_endpoints"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "payload": "{\"fields\":[\"$fields\"]}",
     "target": "field_requests_time"
    }
   ]
  }
 ]
}