{
 "title": "Overview",
 "description": "This dashboard acts as a general overview over all hawk information.",
 "tags": [
  "Service Requests",
  "Endpoint Requests"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard acts as a general overview over all hawk information."
   }
  },
  {
   "title": "Endpoint & Service Requests Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Service Requests",
   "type": "piechart",
   "description": "A Chart that shows how often different services were requested in the specified time span. This is an aggregated count over all service endpoints.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "service_requests_table" }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "target": "endpoint_requests_table" }
   ]
  },
  {
   "title": "Endpoint & Service Requests Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Service Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "target": "service_requests_table" }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "target": "endpoint_requests_table" }
   ]
  },
  {
   "title": "Service Initiator Requests",
   "type": "table",
   "description": "A Table that shows the amount of requests of a service drilled down by\nthe initiator service. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  },
  {
   "title": "Endpoint Initiator Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "endpoint_initiator_requests_table"
    }
   ]
  }
 ]
}