apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
  namespace: hawk
data:
  dashboards.yaml: |-
    apiVersion: 1
    providers: 
      - name: 'Hawk'
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
        type: file