apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: hawk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers: 
      - name: grafana
        image: grafana/grafana:8.5.0
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /var/lib/grafana/dashboards/Hawk
            name: grafana-dashboards
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-providers
        env:
          - name: GF_INSTALL_PLUGINS
            value: simpod-json-datasource 0.3.0, novatec-sdg-panel 4.0.3  
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: json-datasource
        - name: grafana-dashboards
          configMap:
              defaultMode: 420
              name: hawk-dashboards
        - name: grafana-providers
          configMap:
              defaultMode: 420
              name: grafana-providers
      securityContext:
        fsGroup: 472
        runAsUser: 472
        supplementalGroups:
          - 0
      
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: hawk
spec:
  selector: 
    app: grafana
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000