{
 "title": "Hawk-monitor-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Field requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "payload": "{\"fields\":[\"1\"]}",
     "target": "field_requests_time"
    }
   ]
  },
  {
   "title": "Service Initiator Requests",
   "type": "table",
   "description": "A Table that shows the amount of requests of a service drilled down by\nthe initiator service. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  },
  {
   "title": "Service Mesh Graph",
   "type": "novatec-sdg-panel",
   "description": "The main panel of the Service Graph Dashboard. It shows the different\nservices of the cloud system and how many API requests occur between them.\nMoreover, this panel highlights the data flow and direction through animated packages\nthat flow between the services. This panel acts as an entry point for analysis and as an\nat glance overview.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "service_initiator_requests_table"
    }
   ]
  },
  {
   "title": "Service Requests",
   "type": "barchart",
   "description": "A Table that shows how often different services were requested in the\nspecified time span. This is an aggregated count over all service endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "service_requests_table" }
   ]
  }
 ]
}