{{if .Values.istio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: collector-go-service
spec:
  type: ClusterIP
  selector:
    app: collector-go
  ports:
  - port: 80
    targetPort: 8080
{{ end }}