{{if .Values.istio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.13-management
        ports:
          - name: queue
            protocol: TCP
            containerPort: 5672
          - name: admin
            protocol: TCP
            containerPort: 15672
{{ end }}