apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "hawk.fullname" . }}-grafana"
  labels:
    {{- include "hawk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "hawk.fullname" . }}-grafana"
  template:
    metadata:
      {{- with .Values.grafana.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "hawk.fullname" . }}-grafana"
    spec:
      {{- with .Values.grafana.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hawk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.grafana.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ include "hawk.fullname" . }}-grafana"
          securityContext:
            {{- toYaml .Values.grafana.securityContext | nindent 12 }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
          - name: GF_INSTALL_PLUGINS
            value: simpod-json-datasource 0.3.0,novatec-sdg-panel
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: grafana
            mountPath: /etc/grafana/provisioning/datasources/hawk-datasource.yaml
            subPath: hawk-datasource.yaml
            readOnly: true
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      volumes:
      - configMap:
          name: grafana
          items:
          - key: hawk-datasource.yaml
            path: hawk-datasource.yaml
        name: "{{ include "hawk.fullname" . }}-grafana"
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
