apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "hawk.fullname" . }}-nginx"
  labels:
    {{- include "hawk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "hawk.fullname" . }}-nginx"
  template:
    metadata:
      {{- with .Values.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "hawk.fullname" . }}-nginx"
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hawk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ include "hawk.fullname" . }}-nginx"
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/app.conf
            subPath: app.conf
            readOnly: true
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      volumes:
      - configMap:
          name: nginx
          items:
          - key: app.conf
            path: app.conf
        name: "{{ include "hawk.fullname" . }}-nginx"
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
