apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: "{{ include "hawk.fullname" . }}-nginx"
  labels:
    {{- include "hawk.labels" . | nindent 4 }}
data:
  app.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
      location /grafana {
        proxy_pass http://{{ include "hawk.fullname" . }}-grafana;
      }
      location /api {
        proxy_pass http://{{ include "hawk.fullname" . }}-service;
      }
      location / {
        proxy_pass http://{{ include "hawk.fullname" . }}-monitor;
      }
    }